<?xml version="1.0"?>

<!DOCTYPE student [
<!ELEMENT student (name, tel+, email?, alias*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT alias (#PCDATA)>
]>

<student>
  <name>홍길동</name>
  <tel>1111-1592</tel>
  <tel>1421-1592</tel>
  <tel>1166-1592</tel>
  <email>hong@test.com</email>
  <alias>오소리</alias>
</student>
